### ISSUE TITLE
Pickling issues with numpy 1.10

### ISSUE THREAD

**Issue by SimonHeybrock** [DMSC-Instrument-Data/live-data-prototype#36]
Everything works with Numpy 1.8.2, but we get this error with Numpy 1.10:
```
FrameworkManager-[Notice] Welcome to Mantid 3.5.20160112.1019
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
2016-02-03 08:53:17.771 - INFO - zmq_queue - Starting ZMQQueueServer
2016-02-03 08:53:17.772 - INFO - zmq_queue - ZMQQueueServer: Bound to tcp://*:11000
2016-02-03 08:53:17.773 - INFO - backend_event_listener - Starting EventListener...
2016-02-03 08:53:17.773 - INFO - backend_event_listener - Connected to event streamer at tcp://localhost:10001
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/celine/development/live-data-prototype-master/backend/backend_worker.py", line 28, in run
    self._try_process_data()
  File "/home/celine/development/live-data-prototype-master/backend/backend_worker.py", line 57, in _try_process_data
    while not self._process_data():
  File "/home/celine/development/live-data-prototype-master/backend/backend_event_listener.py", line 32, in _process_data
    split_data = self._distribute_stream(what, data)
  File "/home/celine/development/live-data-prototype-master/backend/backend_event_listener.py", line 70, in _distribute_stream
    data = self._comm.scatter(split, root=0)
  File "MPI/Comm.pyx", line 1286, in mpi4py.MPI.Comm.scatter (src/mpi4py.MPI.c:109079)
  File "MPI/msgpickle.pxi", line 716, in mpi4py.MPI.PyMPI_scatter (src/mpi4py.MPI.c:48250)
  File "MPI/msgpickle.pxi", line 143, in mpi4py.MPI.Pickle.load (src/mpi4py.MPI.c:41248)
ValueError: non-string names in Numpy dtype unpickling
```

**Comment by lottiegreenwood** [comment]
also an issue with numpy 1.9, version shipped with windows mantid release
